import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function read(relativePath) {
  return readFileSync(path.join(__dirname, relativePath), 'utf8');
}

test('OpenBrain is a sidebar-controlled page, not an editor tab', () => {
  const appSource = read('./App.tsx');
  const sidebarSource = read('./components/Sidebar/Sidebar.tsx');
  const appStoreSource = read('./store/appStore.ts');

  assert.match(appSource, /const showOpenBrainPage = sidebarView === 'openbrain';/);
  assert.match(appSource, /const showMessengerView = sidebarView === 'messenger';/);
  assert.match(appSource, /const showSpecialPage = showOpenBrainPage \|\| showMessengerView;/);
  assert.match(appSource, /const showComposerDock = composerVisible;/);
  assert.doesNotMatch(appSource, /showMessengerPage/);
  assert.doesNotMatch(appSource, /MessengerPage/);
  assert.match(appSource, /\{showOpenBrainPage \? \(\s*<div className="relative min-w-0 flex-1" ref=\{openBrainPagePaneRef\}>/m);
  assert.match(appSource, /\) : showMessengerView \? \(\s*<div className="relative min-w-0 flex-1" ref=\{messengerConversationPaneRef\}>/m);
  assert.match(appSource, /\{!selectedConversationTarget && \(\s*<MessengerConversationSurface[\s\S]*?selected=\{false\}[\s\S]*?loading=\{messengerSurfaceLoading\}/m);
  assert.doesNotMatch(appSource, /authRequired=\{!authLoggedIn\}/);
  assert.doesNotMatch(appSource, /Messenger needs your OpenBrain account to load agent conversations\./);
  assert.match(appSource, /const activityVisible = Boolean\(selectedConversationTarget\)/m);
  assert.match(appSource, /hasPersistentPlanActivity \|\| threadConversationSelected/);
  assert.match(appSource, /const showActivityPanel = activityVisible;/);
  assert.match(
    appSource,
    /<OpenBrainPage onOpenWorkspace=\{handleOpenBrainWorkspace\} onCreateSource=\{handleCreateOpenBrainSource\} onBindSource=\{handleBindOpenBrainSource\} \/>\s*\{renderActivityPanel\(\)\}/m,
  );
  assert.match(appSource, /\{!showSpecialPage && <EditorTabBar \/>\}/);
  assert.match(appSource, /\{showComposerDock && \(/);
  assert.match(appSource, /<ConversationComposerDock showTopBorder=\{false\} \/>/);
  assert.match(appSource, /const threadConversationSelected = selectedConversationTarget\?\.kind === 'thread'[\s\S]*&& \(composerVisible \|\| showSpecialPage\);/);
  assert.match(appSource, /forceVisible=\{threadConversationSelected\}/);
  assert.doesNotMatch(appSource, /messengerThreadSelected/);
  assert.doesNotMatch(appSource, /composerThreadSelected/);
  assert.match(appSource, /const handleSelectWorkspaceTab = \(tabId: string\) => \{/);
  assert.match(appSource, /if \(showSpecialPage\) \{\s*useUiStore\.getState\(\)\.setSidebarView\('workspace'\);/);
  assert.match(appSource, /onSelectTab=\{handleSelectWorkspaceTab\}/);
  assert.doesNotMatch(appStoreSource, /openOpenBrainTab/);
  assert.doesNotMatch(sidebarSource, /openOpenBrainTab\(\)/);
});

test('OpenBrain workspace selection reuses an existing local workspace tab', () => {
  const appSource = read('./App.tsx');

  assert.match(appSource, /const activateExistingLocalWorkspaceTab = async \(path: string\): Promise<boolean> => \{/);
  assert.match(appSource, /const targetKey = normalizeWorkspacePathKey\(path\);/);
  assert.match(appSource, /const existingTab = useTabManagerStore\.getState\(\)\.tabs\.find\(\(tab\) => \{/);
  assert.match(appSource, /normalizeWorkspacePathKey\(tab\.workspacePath\) === targetKey\s*\|\|\s*normalizeWorkspacePathKey\(storeState\.currentDir\) === targetKey/s);
  assert.match(appSource, /setActiveWorkspaceTab\(existingTab\.id\);/);
  assert.match(appSource, /if \(await activateExistingLocalWorkspaceTab\(path\)\) \{\s*await useRecentWorkspacesStore\.getState\(\)\.recordLocal\(\{ path \}\);\s*return;\s*\}\s*const tab = createWorkspaceTab\(\{ kind: 'local', workspacePath: path \}\);/s);
});

test('OpenBrain login does not auto-create a cloud workspace', () => {
  const appSource = read('./App.tsx');

  assert.match(appSource, /if \(!loginGatedStartup \|\| !authLoggedIn\) \{/);
  assert.doesNotMatch(appSource, /templateID: 'openbrain-cloud'[\s\S]*name: 'workspace'/);
});

test('OpenBrain sidebar add source supports local and remote folders', () => {
  const appSource = read('./App.tsx');
  const directoryPickerSource = read('./components/FileDialog/DirectoryPickerDialog.tsx');
  const addPopoverSource = read('./components/OpenBrain/MyGBrainAddPopover.tsx');
  const openBrainStoreSource = read('./store/openBrainStore.ts');
  const openBrainServiceSource = read('./services/openBrainService.ts');
  const toastViewportSource = read('./components/ToastViewport.tsx');
  const workspaceSource = read('../main/workspace/openbrainWorkspace.ts');

  assert.match(appSource, /const handleCreateOpenBrainSource = async \(\) => \{/);
  assert.match(appSource, /const handleBindOpenBrainSource = async \(workspace: LocalOpenBrainWorkspace\) => \{/);
  assert.match(appSource, /openBrainRuntimeConnectionForWorkspace\(workspace\)/);
  assert.match(appSource, /workspace\.runtimeReachable === false \|\| !targetTab/);
  assert.match(appSource, /const isOpenBrainBindingError = \(error: unknown\) => \{/);
  assert.match(appSource, /code === 'workspace_unbound'[\s\S]*code === 'workspace_path_missing'[\s\S]*code === 'workspace_repo_mismatch'/);
  assert.match(appSource, /if \(isOpenBrainBindingError\(error\)\) \{[\s\S]*await handleBindOpenBrainSource\(workspace\);/);
  assert.match(appSource, /provider === 'cloud' && !openBrainState\.cloudReady/);
  assert.match(appSource, /openStorageBackendSettings\?\.\(\{ storageBackend: 'github' \}\)/);
  assert.match(appSource, /if \(remoteSession\) \{[\s\S]*source: 'create-openbrain-source',[\s\S]*locationKind: 'remote',[\s\S]*tabId: activeTabId/s);
  assert.match(appSource, /source: 'create-openbrain-source',[\s\S]*locationKind: 'local'/s);
  assert.match(appSource, /createRemoteDirectoryPickerProvider\(\{[\s\S]*remoteSession: store\.remoteSession,[\s\S]*listDirectory: store\.listDirectory,[\s\S]*statPath: store\.statPath/s);
  assert.match(appSource, /remotePath: path,[\s\S]*tabId: request\.tabId \|\| activeTabId,[\s\S]*remoteHost: activeTab\?\.remoteHost/s);
  assert.match(appSource, /onCreateOpenBrainSource=\{handleCreateOpenBrainSource\}/);
  assert.match(appSource, /asyncSelect=\{directoryPickerRequest\?\.source === 'create-openbrain-source'\}/);
  assert.match(directoryPickerSource, /asyncSelect\?: boolean/);
  assert.match(directoryPickerSource, /if \(asyncSelect\) \{[\s\S]*onClose\(\);[\s\S]*void onSelect\(path\)\.catch/s);
  assert.match(directoryPickerSource, /import \{ createPortal \} from 'react-dom';/);
  assert.match(directoryPickerSource, /return createPortal\(/);
  assert.match(directoryPickerSource, /className="no-drag fixed inset-0 z-\[130\] flex items-center justify-center"/);
  assert.match(directoryPickerSource, /className="absolute inset-0 bg-black\/50" onMouseDown=\{onClose\}/);
  assert.match(directoryPickerSource, /className="relative flex/);
  assert.match(directoryPickerSource, /document\.body/);
  assert.match(addPopoverSource, /closeBeforeAction\?: boolean/);
  assert.match(addPopoverSource, /onClick=\{\(\) => void runAction\(onCreateSource, \{ closeBeforeAction: true \}\)\}/);
  assert.match(toastViewportSource, /fixed left-4 top-10/);
  assert.match(openBrainStoreSource, /githubConnected: boolean/);
  assert.match(openBrainStoreSource, /cloudReady: boolean/);
  assert.match(openBrainStoreSource, /providerStatusChecked: boolean/);
  assert.match(openBrainStoreSource, /refreshing: boolean/);
  assert.match(openBrainStoreSource, /hydrateCachedSources: \(workspaceTabId\?: string\) => Promise<LocalOpenBrainWorkspace\[\]>/);
  assert.match(openBrainStoreSource, /refreshInBackground: \(workspaceTabId\?: string, options\?: RefreshInBackgroundOptions\) => Promise<LocalOpenBrainWorkspace\[\]>/);
  assert.match(openBrainStoreSource, /export type RefreshInBackgroundOptions = \{[\s\S]*force\?: boolean;/);
  assert.match(openBrainStoreSource, /const OPENBRAIN_REFRESH_TTL_MS = 60_000;/);
  assert.match(openBrainStoreSource, /refreshProviderStatus: \(\) => Promise<OpenBrainProviderStatus>/);
  assert.match(openBrainStoreSource, /getOpenBrainProviderStatus/);
  assert.match(openBrainStoreSource, /const providerStatus = await getOpenBrainProviderStatus\(\);[\s\S]*set\(providerStatusState\(providerStatus, get\(\)\.provider\)\);/);
  assert.match(openBrainStoreSource, /providerStatusChecked: true/);
  assert.match(openBrainStoreSource, /runtimeTabIDsForOpenBrainRefresh\(workspaceTabId\)/);
  assert.match(openBrainStoreSource, /loadSourcesForRuntime\(runtimeTabId, provider/);
  assert.match(openBrainStoreSource, /const statusState = providerStatus[\s\S]*\? providerStatusState\(providerStatus, provider\)[\s\S]*providerStatusChecked: true/);
  assert.match(openBrainStoreSource, /\.\.\.statusState,/);
  assert.match(openBrainServiceSource, /options\?: \{ includeSelf\?: boolean \}/);
  assert.match(openBrainServiceSource, /params\.set\('includeSelf', 'true'\);/);
  assert.match(openBrainStoreSource, /owned: boolean;/);
  assert.match(openBrainStoreSource, /owned: entry\.owned === true/);
  assert.match(openBrainStoreSource, /\(entry\.followed \|\| entry\.owned \|\| entry\.member\) && publicBrainHasActiveSources\(entry\)/);
  assert.match(openBrainStoreSource, /listOpenBrainPublicBrains\('', workspaceTabId, \{ includeSelf: true \}\)/);
  assert.match(openBrainStoreSource, /listOpenBrainPublicBrains\(query, undefined, \{ includeSelf: true \}\)/);
  assert.doesNotMatch(openBrainServiceSource, /resolveOpenBrainPublicBrainSources/);
  assert.doesNotMatch(openBrainServiceSource, /public-brains\/.+\/sources/);
  assert.match(openBrainStoreSource, /loadFollowedPublicBrainsForStore/);
  assert.match(openBrainStoreSource, /publicBrains: provider === 'local' \? \[\] : get\(\)\.publicBrains/);
  assert.match(openBrainStoreSource, /catch \{[\s\S]*publicBrains: current,[\s\S]*loaded: false,/);
  assert.doesNotMatch(openBrainStoreSource, /SubscribedPublicBrain/);
  assert.match(addPopoverSource, /entry\.owned \? \(/);
  assert.match(addPopoverSource, /entry\.owned[\s\S]*\? Promise\.resolve\(\)/);
  assert.match(openBrainStoreSource, /const request = \{[\s\S]*name: trimmedName,[\s\S]*localPath: targetPath,/s);
  assert.match(openBrainStoreSource, /let result = await createOpenBrainSource\(request, workspaceTabId, \{ provider \}\);/);
  assert.match(openBrainStoreSource, /cleanupError\?: string;/);
  assert.match(openBrainStoreSource, /function openBrainCreateSourceRuntimeError/);
  assert.match(openBrainStoreSource, /Cleanup rollback failed: \$\{cleanupError\}/);
  assert.match(openBrainStoreSource, /throw openBrainCreateSourceRuntimeError\(result, provider\);/);
  assert.match(openBrainStoreSource, /await get\(\)\.refresh\(workspaceTabId\)\.catch\(\(\) => \{\s*set\(\{[\s\S]*sources: linkedSources,[\s\S]*loading: false,[\s\S]*lastLoadedAt: Date\.now\(\),[\s\S]*\}\);[\s\S]*return linkedSources;/);
  assert.match(workspaceSource, /stderr\.trim\(\) \|\| stdout\.trim\(\) \|\| `git \$\{args\.join\(' '\)\} failed with exit code \$\{code\}`/);
});

test('OpenBrain sidebar removes sources without deleting local files', () => {
  const sidebarSource = read('./components/Sidebar/OpenBrainSidebar.tsx');
  const sourceActionsSource = read('./components/OpenBrain/CloudSourceActions.tsx');
  const openBrainPageSource = read('./components/OpenBrain/OpenBrainPage.tsx');
  const flowGraphSource = read('./components/OpenBrain/OpenBrainFlowGraph.tsx');
  const flowSource = read('./components/OpenBrain/openBrainFlow.ts');
  const openBrainStoreSource = read('./store/openBrainStore.ts');
  const openBrainServiceSource = read('./services/openBrainService.ts');
  const workspaceSource = read('../main/workspace/openbrainWorkspace.ts');
  const removeFunction = workspaceSource.match(/export async function removeOpenBrainWorkspaceFromDevice[\s\S]*?\n}\n\nexport async function findIndexedOpenBrainWorkspaceByPath/)?.[0] || '';
  const sourceActionSurface = `${sidebarSource}\n${sourceActionsSource}\n${openBrainPageSource}\n${flowGraphSource}`;
  const sourceGraphNodeSource = flowGraphSource.match(/function SourceGraphNode[\s\S]*?\n}\n\nfunction GraphNode/)?.[0] || '';

  assert.doesNotMatch(sourceActionSurface, /Remove from this device/);
  assert.doesNotMatch(sourceActionSurface, /Stop cloud queries/);
  assert.doesNotMatch(sourceActionSurface, /Cloud source actions\.\.\./);
  assert.match(sourceActionsSource, /Share source\.\.\./);
  assert.match(sourceActionsSource, /const canManage = canManageOpenBrainSource\(source\);/);
  assert.match(sourceActionsSource, /onShareSource && canManage/);
  assert.match(sourceActionsSource, /showCloudManagement && onShareSource && canManage/);
  assert.match(sourceActionsSource, /showCloudManagement && canManage/);
  assert.match(sourceActionsSource, /onToggleSourceLink/);
  assert.match(sourceActionsSource, /Disconnect source/);
  assert.match(sourceActionsSource, /Connect source/);
  assert.match(sourceActionsSource, /\{showCloudManagement && canManage \? \(/);
  assert.match(sourceActionsSource, /Disable cloud queries/);
  assert.match(sourceActionsSource, /Enable cloud queries/);
  assert.match(sourceActionsSource, /Turn off sync/);
  assert.match(sourceActionsSource, /Permanently delete this cloud source\.\.\./);
  assert.match(sourceActionsSource, /queriesDisabled \? \{ enableQueries: true \} : \{ disableQueries: true \}/);
  assert.match(sourceActionsSource, /onApplyAction\(source, \{ disableSync: true \}\)/);
  assert.match(sidebarSource, /CloudSourceActionMenuItems/);
  assert.match(sidebarSource, /HardDeleteCloudSourceDialog/);
  assert.doesNotMatch(sourceActionSurface, /type="checkbox"/);
  assert.match(sourceActionsSource, /Local files, the GitHub repository, and other accounts' cloud sources for the same repo will not be deleted/);
  assert.match(sourceActionsSource, /Workspace ID/);
  assert.match(sourceActionsSource, /Source ID/);
  assert.match(sourceActionsSource, /Repo/);
  assert.match(sourceActionsSource, /Review before deleting/);
  assert.match(sourceActionsSource, /Clicking Delete cloud source is the second confirmation/);
  assert.match(sourceActionsSource, /createPortal/);
  assert.match(sourceActionsSource, /document\.body/);
  assert.match(sourceActionsSource, /no-drag pointer-events-auto fixed inset-0 z-\[90\]/);
  assert.match(sourceActionsSource, /onMouseDown=\{handleCancelMouseDown\}/);
  assert.match(sourceActionsSource, /onMouseDown=\{handleDeleteMouseDown\}/);
  assert.match(sourceActionsSource, /confirmWorkspaceID: workspaceID/);
  assert.match(sourceActionsSource, /confirmName: sourceName/);
  assert.doesNotMatch(sourceActionsSource, /placeholder=\{/);
  assert.doesNotMatch(sourceActionsSource, /setConfirmName/);
  assert.doesNotMatch(sourceActionsSource, /setConfirmWorkspaceID/);
  assert.match(sourceActionsSource, /confirmWorkspaceID/);
  assert.match(sourceActionsSource, /confirmName/);
  assert.doesNotMatch(flowGraphSource, /openbrain-source-menu-button/);
  assert.doesNotMatch(flowGraphSource, /onContextMenuCapture=\{sourceContextMenuEnabled \? \(event\) => openSourceContextMenu\(node, event\) : undefined\}/);
  assert.match(sourceGraphNodeSource, /className=\{`openbrain-source-node openbrain-flow-node-button nodrag nopan/);
  assert.doesNotMatch(flowGraphSource, /openbrain-source-main-button/);
  assert.match(flowGraphSource, /function SourceGraphNode/);
  assert.match(flowGraphSource, /export type OpenBrainFlowSourceContextMenuEvent =/);
  assert.doesNotMatch(flowGraphSource, /React\.PointerEvent<Element>/);
  assert.doesNotMatch(flowGraphSource, /const stopFlowGesture = /);
  assert.doesNotMatch(flowGraphSource, /onMouseDownCapture=\{stopFlowGesture\}/);
  assert.doesNotMatch(flowGraphSource, /onPointerDownCapture=\{openMenu\}/);
  assert.match(sourceGraphNodeSource, /data\.publicAccess \? ' openbrain-source-public' : ''/);
  assert.match(sourceGraphNodeSource, /const handleClick = \(event: React\.MouseEvent<HTMLButtonElement>\) => \{/);
  assert.match(sourceGraphNodeSource, /data\.onNodeAction\?\.\(node, event\);/);
  assert.match(sourceGraphNodeSource, /onClick=\{handleClick\}/);
  assert.match(sourceGraphNodeSource, /onContextMenu=\{sourceContextMenuEnabled \? openMenu : undefined\}/);
  assert.match(flowGraphSource, /const handleNodeClick = \(\s*event: React\.MouseEvent,\s*node: OpenBrainRenderedFlowNode,\s*\) => \{/);
  assert.match(flowGraphSource, /if \(node\.data\.kind !== 'source' \|\| !node\.data\.onNodeAction\)/);
  assert.doesNotMatch(flowGraphSource, /if \(event\.detail > 1\)/);
  assert.doesNotMatch(openBrainPageSource, /NODE_SINGLE_CLICK_DELAY_MS/);
  assert.doesNotMatch(openBrainPageSource, /scheduleNodeSingleClick/);
  assert.match(openBrainPageSource, /const disconnectPublicBrain = useCallback/);
  assert.match(openBrainPageSource, /unfollowPublicBrain\(ownerUID\)/);
  assert.match(openBrainPageSource, /setSourceLinked\(sourceKey, !isSourceLinked\(sourceKey\)\)/);
  assert.match(openBrainPageSource, /disconnectPublicBrain\(node\)/);
  assert.match(openBrainPageSource, /startPublicBrainChat\(node\)/);
  assert.doesNotMatch(openBrainPageSource, /const toggleCloudSourceQueries = useCallback/);
  assert.match(sourceActionsSource, /queriesDisabled \? \{ enableQueries: true \} : \{ disableQueries: true \}/);
  assert.match(sourceActionsSource, /onChatWithSource/);
  assert.match(sourceActionsSource, /onToggleSourceLink/);
  assert.match(openBrainPageSource, /startSourceChat\(workspace\)/);
  assert.match(openBrainPageSource, /startSourceChat\(source\)/);
  assert.doesNotMatch(flowGraphSource, /target\?\.closest\('\.openbrain-source-menu-button'\)/);
  assert.match(flowGraphSource, /onNodeClick=\{handleNodeClick\}/);
  assert.match(flowGraphSource, /onNodeContextMenu=\{handleNodeContextMenu\}/);
  assert.match(flowGraphSource, /openSourceContextMenu\(\{ \.\.\.node\.data, id: node\.id \}, event\);/);
  assert.match(flowSource, /sourceID\?: string;/);
  assert.match(flowSource, /sourceID: workspace\?\.sourceID/);
  assert.match(flowSource, /instanceID\?: string;/);
  assert.match(flowSource, /instanceID: workspace\?\.instanceID/);
  assert.match(flowSource, /runtimeReachable\?: boolean;/);
  assert.doesNotMatch(flowSource, /runtimeLabel\?: string;/);
  assert.doesNotMatch(flowSource, /function workspaceSubtitle/);
  assert.doesNotMatch(flowSource, /export function resolveSourceNodeSubtitle/);
  assert.match(flowSource, /publicAccess\?: boolean;/);
  assert.match(flowSource, /canMutateSource\?: boolean;/);
  assert.match(flowSource, /bindingMode\?: 'own' \| 'granted';/);
  assert.match(openBrainPageSource, /resolveOpenBrainSourceDisplayState/);
  assert.match(openBrainPageSource, /sourceDisplay\?\.statusText/);
  assert.match(openBrainPageSource, /sourceDisplay\?\.arcLinked/);
  assert.doesNotMatch(openBrainPageSource, /runtimeLabel: workspace\.runtimeLabel/);
  assert.match(openBrainPageSource, /sourceID: workspace\.sourceID/);
  assert.match(openBrainPageSource, /instanceID: workspace\.instanceID/);
  assert.match(openBrainPageSource, /runtimeReachable: workspace\.runtimeReachable/);
  assert.match(openBrainPageSource, /publicAccess: workspace\.publicAccess === true/);
  assert.match(openBrainPageSource, /node\.sourceID \? workspaceByID\.get\(node\.sourceID\) : null/);
  assert.match(sidebarSource, /resolveOpenBrainSourceDisplayState/);
  assert.match(sidebarSource, /display\.detail \?\? display\.statusText/);
  assert.doesNotMatch(sidebarSource, /sourceBindingLabel/);
  assert.doesNotMatch(sidebarSource, /Runtime not connected/);
  assert.match(openBrainStoreSource, /publicAccess\?: boolean;/);
  assert.match(openBrainStoreSource, /canMutateSource\?: boolean;/);
  assert.match(openBrainStoreSource, /export function canManageOpenBrainSource/);
  assert.match(openBrainStoreSource, /function cloudSourceKey/);
  assert.match(openBrainStoreSource, /return `cloud:\$\{orgID\}:\$\{sourceID\}`;/);
  assert.match(openBrainStoreSource, /source\.bindingMode === 'granted'/);
  assert.match(openBrainStoreSource, /source\.effectivePermission === 'read'/);
  assert.match(openBrainStoreSource, /updatePublicBrainProfile: \(description: string\) => Promise<OpenBrainPublicBrainProfile>;/);
  assert.match(openBrainStoreSource, /description: \(entry\.description \|\| ''\)\.trim\(\) \|\| undefined/);
  assert.match(openBrainStoreSource, /updateWorkspacePublicAccess/);
  assert.match(openBrainStoreSource, /share\?\.public\?\.status === 'active'/);
  assert.match(openBrainPageSource, /function sourceContextMenuPosition\(event: OpenBrainFlowSourceContextMenuEvent\)/);
  assert.match(openBrainPageSource, /const hasPointer = Number\.isFinite\(pointerEvent\.clientX\) && Number\.isFinite\(pointerEvent\.clientY\);/);
  assert.match(openBrainPageSource, /const handleSourceContextMenu = useCallback\(\(node: OpenBrainInteractiveNode, event: OpenBrainFlowSourceContextMenuEvent\) => \{/);
  assert.match(openBrainPageSource, /const sourceContextMenuEnabled = Boolean\(\s*!showDemoGraph\s*&& sourceWorkspace\s*&& sourceDisplay/);
  assert.doesNotMatch(openBrainPageSource, /sourceContextMenuEnabled[\s\S]{0,180}sourceWorkspace\?\.orgID/);
  assert.doesNotMatch(openBrainPageSource, /provider !== 'cloud' \|\| !workspace\.orgID/);
  assert.doesNotMatch(openBrainPageSource, /\.openbrain-flow \.react-flow__node \{[^}]*pointer-events: auto;/);
  assert.doesNotMatch(openBrainPageSource, /openbrain-source-menu-button/);
  assert.match(openBrainPageSource, /\.openbrain-flow-node \{[\s\S]*pointer-events: auto;/);
  assert.doesNotMatch(openBrainPageSource, /const openSourceWorkspace = useCallback/);
  assert.doesNotMatch(openBrainPageSource, /if \(!showDemoGraph && provider === 'cloud' && workspace\) \{\s*return;\s*\}/);
  assert.doesNotMatch(openBrainPageSource, /toggleCloudSourceQueries/);
  assert.doesNotMatch(openBrainPageSource, /if \(provider === 'cloud'\) \{\s*return;\s*\}/);
  assert.match(sourceActionsSource, /queriesDisabled \? \{ enableQueries: true \} : \{ disableQueries: true \}/);
  assert.doesNotMatch(openBrainPageSource, /void handleApplySourceAction\(workspace, action\);/);
  assert.match(openBrainPageSource, /sourceDisplay\?\.arcLinked/);
  assert.match(sidebarSource, /!canManageOpenBrainSource\(brain\)/);
  assert.match(sidebarSource, /const hydrateCachedSources = useOpenBrainStore\(\(state\) => state\.hydrateCachedSources\);/);
  assert.match(sidebarSource, /await hydrateCachedSources\(\)\.catch\(\(\) => \[\]\)/);
  assert.match(sidebarSource, /disabled=\{mutating\}/);
  assert.doesNotMatch(sidebarSource, /disabled=\{!brain\.path \|\| mutating\}/);
  assert.doesNotMatch(sidebarSource, /'Cloud source'/);
  assert.doesNotMatch(sidebarSource, /Cloud-only OpenBrain source/);
  assert.doesNotMatch(sidebarSource, /cloud-only on this device/);
  assert.match(openBrainPageSource, /const isUnlinkedSourceEdge = edge\.data\?\.kind === 'source'[\s\S]*target\?\.data\.kind === 'source'[\s\S]*!targetLinked;/);
  assert.match(openBrainPageSource, /\|\| isUnlinkedSourceEdge/);
  assert.match(openBrainPageSource, /setSourceContextMenu\(\{\s*source: workspace,[\s\S]*sourceContextMenuPosition\(event\),[\s\S]*\}\);/);
  assert.match(openBrainPageSource, /createPortal\(/);
  assert.match(openBrainPageSource, /aria-label="Close source menu"/);
  assert.match(openBrainPageSource, /onMouseDown=\{\(\) => setSourceContextMenu\(null\)\}/);
  assert.doesNotMatch(openBrainPageSource, /window\.addEventListener\('mousedown', handleMouseDown, true\)/);
  assert.match(openBrainPageSource, /onShareSource=\{\(source\) => void handleShareSource\(source\)\}/);
  assert.match(openBrainPageSource, /onApplyAction=\{\(source, action\) => void handleApplySourceAction\(source, action\)\}/);
  assert.match(openBrainStoreSource, /removeFromDevice: \(workspace: LocalOpenBrainWorkspace\) => Promise<void>/);
  assert.match(openBrainStoreSource, /archiveSource: \(workspace: LocalOpenBrainWorkspace\) => Promise<void>/);
  assert.match(openBrainStoreSource, /applySourceAction: \(workspace: LocalOpenBrainWorkspace, action: OpenBrainSourceActionOptions\) => Promise<OpenBrainSourceActionResponse>/);
  assert.match(openBrainStoreSource, /removeOpenBrainSourceFromDevice\(workspaceIdentityPayload\(workspace\), routeTabIDForWorkspace\(workspace\)\)/);
  assert.match(openBrainStoreSource, /archiveOpenBrainSource\(workspaceIdentityPayload\(workspace\), routeTabIDForWorkspace\(workspace\)\)/);
  assert.match(openBrainStoreSource, /applyOpenBrainSourceAction\(\{[\s\S]*\.\.\.workspaceIdentityPayload\(workspace\),[\s\S]*\.\.\.action,/);
  assert.match(openBrainStoreSource, /const removesFromDevice = action\.hardDelete \|\| result\.hardDeleted/);
  assert.match(openBrainStoreSource, /updateWorkspaceQueriesDisabled/);
  assert.match(openBrainStoreSource, /const togglesQueries = action\.disableQueries === true \|\| action\.enableQueries === true/);
  assert.match(openBrainStoreSource, /const previousSources = get\(\)\.sources/);
  assert.match(openBrainStoreSource, /if \(togglesQueries\) \{[\s\S]*updateWorkspaceQueriesDisabled\(/);
  assert.match(openBrainStoreSource, /set\(\{ sources: previousSources \}\);/);
  assert.doesNotMatch(openBrainStoreSource, /action\.hardDelete \|\| action\.disableQueries \|\| result\.hardDeleted \|\| result\.disabledQueries/);
  assert.match(openBrainServiceSource, /\/v1\/openbrain\/cloud\/sources\/action/);
  assert.match(removeFunction, /await saveWorkspaceIndex\(homeDir, index\)/);
  assert.doesNotMatch(removeFunction, /fs\.(?:rm|unlink|rmdir)|runSsh|runGitCommand|spawn/i);
  assert.doesNotMatch(sourceActionSurface, /DeleteConfirmDialog/);
});

test('OpenBrain Cloud re-add reuses existing GitHub-backed cloud workspace', () => {
  const serverSource = read('../../../server/internal/server/gbrain/cloud.go');
  const workspaceSource = read('../main/workspace/openbrainWorkspace.ts');

  assert.match(serverSource, /func \(s \*Service\) resolveOrCreateCloudWorkspace/);
  assert.match(serverSource, /resolved, err := s\.resolveCloudWorkspaceByRepo/);
  assert.match(serverSource, /if cloudWorkspaceResolveFound\(resolved\) \{/);
  assert.match(serverSource, /return createWorkspaceResultFromResolvedWorkspace\(resolved\.Workspace, repo, resolved\), false, nil/);
  assert.match(workspaceSource, /hiddenWorkspaces/);
  assert.match(workspaceSource, /removeOpenBrainWorkspaceFromDevice/);
  assert.match(workspaceSource, /isOpenBrainWorkspaceHidden/);
  assert.match(workspaceSource, /index\.hiddenWorkspaces = \(index\.hiddenWorkspaces \|\| \[\]\)\.filter/);
});

test('OpenBrain Cloud add binds existing GitHub directories before background sync', () => {
  const serverSource = read('../../../server/internal/server/gbrain/cloud.go');

  assert.match(serverSource, /createdNewCloudSource := false/);
  assert.match(serverSource, /created, createdNewCloudSource, err = s\.resolveOrCreateCloudWorkspace/);
  assert.match(serverSource, /if createdNewCloudSource && repo == nil \{[\s\S]*s\.fetchWorkspaceGitToken/s);
  assert.match(serverSource, /if createdNewCloudSource \{[\s\S]*s\.triggerBrainSync/s);
});

test('OpenBrain Cloud recovery candidates are checked by runtime server and require confirmation', () => {
  const appSource = read('./App.tsx');
  const openBrainServiceSource = read('./services/openBrainService.ts');
  const openBrainStoreSource = read('./store/openBrainStore.ts');
  const providerSource = read('../main/openbrain/brainProvider.ts');

  assert.match(openBrainServiceSource, /\/v1\/openbrain\/cloud\/sources\/recovery-candidates/);
  assert.match(openBrainStoreSource, /listRecoveryCandidates: \(workspace: LocalOpenBrainWorkspace, paths: string\[\]\)/);
  assert.match(openBrainStoreSource, /listOpenBrainRecoveryCandidates\(\{[\s\S]*workspaceIdentityPayload\(workspace\),[\s\S]*paths,/);
  assert.match(appSource, /collectOpenBrainRecoveryCandidatePaths/);
  assert.match(appSource, /useRecentWorkspacesStore\.getState\(\)\.recent\.local/);
  assert.match(appSource, /getRemoteBucketByInstanceID\(useRecentWorkspacesStore\.getState\(\)\.recent, workspace\.instanceID\)/);
  assert.match(appSource, /listRecoveryCandidates\(workspace, candidatePaths\)/);
  assert.match(appSource, /window\.confirm\(`Bind \$\{workspace\.name\} to \$\{candidate\.path\} on this runtime\?`\)/);
  assert.match(appSource, /createOpenBrain\(\{[\s\S]*source: workspace,/);
  assert.doesNotMatch(providerSource, /bindCloudWorkspacesFromLocalCandidates/);
  assert.doesNotMatch(providerSource, /localWorkspaceCandidates\?: LocalWorkspaceCandidate\[\]/);
});

test('OpenBrain sidebar state uses the OpenBrain key name', () => {
  const sidebarTabsSource = read('./components/Sidebar/sidebarTabs.ts');
  const sidebarSource = read('./components/Sidebar/Sidebar.tsx');

  assert.match(sidebarTabsSource, /'openbrain'/);
  assert.doesNotMatch(sidebarTabsSource, /'brain'/);
  assert.match(sidebarTabsSource, /rendererI18n\.t\('sidebar:rail\.openbrain'\)/);
  assert.match(sidebarSource, /view === 'openbrain'/);
  assert.match(sidebarSource, /<OpenBrainSidebar[\s\S]*onOpenWorkspace=\{handleOpenBrainWorkspace\}[\s\S]*onCreateSource=\{onCreateOpenBrainSource\}[\s\S]*onBindSource=\{onBindOpenBrainSource\}[\s\S]*\/>/);
});

test('OpenBrain graph chat uses GBrain for MyGBrain and default OpenBrain for sources', () => {
  const pageSource = read('./components/OpenBrain/OpenBrainPage.tsx');
  const appStoreSource = read('./store/appStore.ts');

  assert.match(pageSource, /const GBRAIN_AGENT_ID = 'agent-gbrain';/);
  assert.match(pageSource, /prepareWorkspaceRuntimeForChat = async \(workspace: LocalOpenBrainWorkspace\)/);
  assert.match(pageSource, /preparePathForChat = async \(workspace: LocalOpenBrainWorkspace\)/);
  assert.match(pageSource, /const activeInstanceID = \(activeState\.instanceID \|\| ''\)\.trim\(\);/);
  assert.match(pageSource, /const sameRuntime = workspaceInstanceID/);
  assert.match(pageSource, /if \(!sameRuntime \|\| activeState\.currentDir !== normalizedPath\) \{/);
  assert.match(pageSource, /getChatAgentForCwd\(normalizedPath\)/);
  assert.match(pageSource, /refreshAgentNodes\(\{ force: true \}\)/);
  assert.match(pageSource, /getDefaultOpenBrainForCwd\(normalizedPath\)/);
  assert.match(pageSource, /resolveGBrainAgentForCwd = async \(agentCwd: string\)/);
  assert.match(pageSource, /getAgentOpCode\(GBRAIN_AGENT_ID\)/);
  assert.match(pageSource, /resolveAgentByID\(GBRAIN_AGENT_ID\)/);
  assert.match(pageSource, /agentID: GBRAIN_AGENT_ID/);
  assert.match(pageSource, /GBrain agent is not available yet\./);
  assert.match(appStoreSource, /getDefaultOpenBrainForCwd: \(cwd: string\) => \{/);
  assert.match(appStoreSource, /id === 'agent-openbrain'/);
  assert.match(appStoreSource, /agentCwd,/);
});

test('OpenBrain chat uses provider source context and retrieval APIs', () => {
  const pageSource = read('./components/OpenBrain/OpenBrainPage.tsx');
  const chatStoreSource = read('./store/chatWorkspaceStore.ts');
  const chatServiceSource = read('./services/chatService.ts');
  const openBrainServiceSource = read('./services/openBrainService.ts');
  const openBrainStoreSource = read('./store/openBrainStore.ts');

  assert.match(chatStoreSource, /export type GBrainQueryScope/);
  assert.match(chatStoreSource, /kind: 'source';[\s\S]*sourceID: string;/);
  assert.doesNotMatch(chatStoreSource, /kind: 'publicBrain'/);
  assert.match(openBrainStoreSource, /sourceID: string;/);
  assert.match(openBrainStoreSource, /runtimeReachable\?: boolean;/);
  assert.doesNotMatch(openBrainStoreSource, /runtimeTabId\?: string;/);
  assert.match(openBrainStoreSource, /import \{[\s\S]*createOpenBrainSource,[\s\S]*listCachedOpenBrainSources,[\s\S]*listGBrainSources,[\s\S]*removeOpenBrainSourceFromDevice,/);
  assert.match(openBrainStoreSource, /return await listGBrainSources\(workspaceTabId, \{ provider \}\);/);
  assert.match(openBrainStoreSource, /await listCachedOpenBrainSources\(workspaceTabId\)/);
  assert.match(openBrainStoreSource, /const sources = normalizeSources\(rawSources, workspaceTabId\);/);
  assert.match(openBrainStoreSource, /function tabRuntimeReachable\(tab: WorkspaceTab \| null\): boolean/);
  assert.match(openBrainStoreSource, /export function openBrainRuntimeConnectionForWorkspace/);
  assert.match(openBrainStoreSource, /function routeTabIDForWorkspace\(workspace: LocalOpenBrainWorkspace\): string \| undefined/);
  assert.match(openBrainStoreSource, /error\.code = 'runtime_unreachable';/);
  assert.match(openBrainStoreSource, /runtimeReachable: tabRuntimeReachable\(runtimeTab\)/);
  assert.match(openBrainStoreSource, /function markRuntimeReachability\(sources: LocalOpenBrainWorkspace\[\]\): LocalOpenBrainWorkspace\[\]/);
  assert.match(openBrainStoreSource, /let merged = markRuntimeReachability\(get\(\)\.sources\);/);
  assert.match(openBrainStoreSource, /function mergeRuntimeSources/);
  assert.match(openBrainStoreSource, /function resolveInstanceIDForWorkspaceTab/);
  assert.match(openBrainStoreSource, /const instanceID = \(appState\.instanceID \|\| ''\)\.trim\(\)/);
  assert.match(openBrainStoreSource, /source\.instanceID === instanceID/);
  assert.match(openBrainStoreSource, /mergeRuntimeSources\(current, runtimeTabId, sources\)/);
  assert.match(openBrainStoreSource, /function mergeOpenBrainSource/);
  assert.match(openBrainStoreSource, /path: binding\.path \|\| next\.path \|\| existing\.path/);
  assert.match(openBrainStoreSource, /function sameOpenBrainSource/);
  assert.match(openBrainStoreSource, /normalizeOpenBrainRemote\(a\.remoteURL\)/);
  assert.match(openBrainStoreSource, /function upsertRuntimeSource/);
  assert.match(openBrainStoreSource, /const sources = upsertRuntimeSource\(get\(\)\.sources, workspace\);/);
  assert.match(openBrainStoreSource, /sourceMatchesRuntime\(source, workspace\.instanceID\)/);
  assert.match(openBrainStoreSource, /const routeTabId = routeTabIDForWorkspace\(workspace\);/);
  assert.match(openBrainStoreSource, /verifyOpenBrainSource\(workspaceIdentityPayload\(workspace\), routeTabId\)/);
  assert.match(openBrainStoreSource, /result\?\.code,/);
  assert.match(openBrainStoreSource, /createOpenBrainSource\(/);
  assert.doesNotMatch(openBrainStoreSource, /workspace\?\.listOpenBrains/);
  assert.doesNotMatch(openBrainStoreSource, /workspace\?\.createOpenBrain/);
  assert.doesNotMatch(openBrainStoreSource, /rootPath/);
  assert.match(openBrainServiceSource, /resolveOpenBrainBaseUrl/);
  assert.match(openBrainServiceSource, /if \(workspaceTabId && !targetTab\) \{/);
  assert.match(openBrainServiceSource, /throw new Error\('OpenBrain runtime is not connected\.'\);/);
  assert.match(openBrainServiceSource, /if \(targetTab\?\.kind === 'remote'\) \{[\s\S]*throw new Error\('OpenBrain remote runtime is not connected\.'\);/);
  assert.match(openBrainServiceSource, /remoteSession\?\.localPort/);
  assert.match(openBrainServiceSource, /\/v1\/openbrain\/cloud\/sources/);
  assert.match(openBrainServiceSource, /\/v1\/openbrain\/cached-sources/);
  assert.match(openBrainServiceSource, /\/v1\/openbrain\/sources/);
  assert.match(openBrainServiceSource, /\/v1\/openbrain\/cloud\/query/);
  assert.match(openBrainServiceSource, /\/v1\/openbrain\/query/);
  assert.match(openBrainServiceSource, /window\.electronAPI\?\.openBrain\?\.getProvider/);
  assert.match(pageSource, /prepareBrainForChat/);
  assert.match(pageSource, /const prepareBrainForChat = async \(\): Promise<ChatAgentTarget \| null> => \{\s*await waitForWorkspaceConnection\(\);\s*return resolveGBrainAgentForCwd\(''\);\s*\};/s);
  assert.match(pageSource, /return prepareBrainForChat\(\);/);
  assert.doesNotMatch(pageSource, /sources\.find\(\(workspace\) => workspace\.path\)\?\.path/);
  assert.doesNotMatch(pageSource, /return preparedCwd \? resolveGBrainAgentForCwd\(preparedCwd\) : null;/);
  assert.match(pageSource, /workspaceByID/);
  assert.doesNotMatch(pageSource, /sources\[0\]/);
  assert.doesNotMatch(pageSource, /rebuildIndex/);
  assert.doesNotMatch(pageSource, /indexStatus/);
  assert.match(pageSource, /gbrainSourceScopeForWorkspace\(workspace\)/);
  assert.doesNotMatch(pageSource, /publicBrainScopeForNode/);
  assert.doesNotMatch(pageSource, /publicBrainByOwnerUID/);
  assert.match(pageSource, /\.filter\(\(brain\) => brain\.activeSourceCount > 0\)/);
  assert.match(pageSource, /setHostedChatBrain\(\{ brainID: brain\.brainID, name: brain\.name, username: brain\.username \}\)/);
  assert.match(pageSource, /<PublicBrainHostedChatDialog/);
  assert.doesNotMatch(pageSource, /resolveOpenBrainPublicBrainSources/);
  assert.doesNotMatch(pageSource, /openingPublicBrainOwnerUIDRef/);
  assert.doesNotMatch(pageSource, /node\.publicBrainSources/);
  assert.doesNotMatch(pageSource, /Public brain source IDs are not loaded yet/);
  assert.match(pageSource, /This public brain is not available\./);
  assert.match(pageSource, /chatState\.setGBrainQueryScope\(options\?\.scope \|\| null\);/);
  assert.doesNotMatch(chatServiceSource, /import \{ queryOpenBrain \} from '\.\/openBrainService';/);
  assert.doesNotMatch(chatServiceSource, /queryOpenBrain\(\{/);
  assert.doesNotMatch(chatServiceSource, /window\.electronAPI\?\.openbrain/);
  assert.doesNotMatch(chatServiceSource, /api\.query/);
  assert.doesNotMatch(chatServiceSource, /<openbrain_context/);
  assert.doesNotMatch(chatServiceSource, /<user_message>/);
  assert.match(chatServiceSource, /\.\.\.\(chatState\.gbrainQueryScope \? \{ gbrainQueryScope: chatState\.gbrainQueryScope \} : \{\}\),/);
});
