package chat

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"github.com/colinagent/openbrain/opagent-protocol/go-sdk/op"
	"github.com/colinagent/openbrain/server/internal/server/chatindex"
	"github.com/gin-gonic/gin"
)

type ChatRetitleParams struct {
	ThreadID string `json:"threadID,omitempty"`
	FileID   string `json:"fileID,omitempty"`
	ChatPath string `json:"chatPath,omitempty"`
	Title    string `json:"title"`
}

type RetitleHandler struct {
	service *Service
}

var autoNamedChatPathStemRE = regexp.MustCompile(`^(untitled-chat|image)(?:-\d+)?$`)

var retitleThread = func(
	ctx context.Context,
	service *Service,
	query op.ThreadMetaQuery,
	title string,
) (*op.ThreadMeta, error) {
	if service == nil {
		return nil, http.ErrServerClosed
	}
	return service.RetitleThread(ctx, query, title)
}

func NewRetitleHandler(service *Service) *RetitleHandler {
	return &RetitleHandler{service: service}
}

func (h *RetitleHandler) Retitle(c *gin.Context) {
	if h.service == nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "chat service is not initialized"})
		return
	}

	var params ChatRetitleParams
	if err := c.ShouldBindJSON(&params); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid JSON: " + err.Error()})
		return
	}

	params.ThreadID = strings.TrimSpace(params.ThreadID)
	params.FileID = strings.TrimSpace(params.FileID)
	params.ChatPath = strings.TrimSpace(params.ChatPath)
	params.Title = strings.TrimSpace(params.Title)
	if params.ThreadID == "" && params.FileID == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "threadID or fileID is required"})
		return
	}
	if params.Title == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "title is required"})
		return
	}

	meta, err := retitleThread(context.Background(), h.service, op.ThreadMetaQuery{
		ThreadID: params.ThreadID,
		FileID:   params.FileID,
		ChatPath: params.ChatPath,
	}, params.Title)
	if err != nil {
		status := http.StatusBadRequest
		if isThreadNotFound(err) {
			status = http.StatusNotFound
		}
		c.JSON(status, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, meta)
}

func isAutoGeneratedSessionTitle(title string) bool {
	switch strings.ToLower(strings.TrimSpace(title)) {
	case "untitled chat", "untitled thread", "image":
		return true
	default:
		return false
	}
}

func isAutoGeneratedChatPath(chatPath string) bool {
	base := filepath.Base(strings.TrimSpace(chatPath))
	stem := strings.TrimSuffix(base, filepath.Ext(base))
	return autoNamedChatPathStemRE.MatchString(strings.ToLower(strings.TrimSpace(stem)))
}

func shouldMigrateRetitledChatPath(meta *op.ThreadMeta, currentChatPath string, nextTitle string) bool {
	if meta == nil {
		return false
	}
	if isAutoGeneratedSessionTitle(nextTitle) {
		return false
	}
	return isAutoGeneratedChatPath(currentChatPath)
}

func resolveRetitleCWD(meta *op.ThreadMeta, currentChatPath string) string {
	if meta != nil {
		if cwd := strings.TrimSpace(meta.CWD); cwd != "" {
			return cwd
		}
	}
	return strings.TrimSpace(chatPathQueryCWD(currentChatPath))
}

func buildRetitledChatPath(meta *op.ThreadMeta, currentChatPath string, nextTitle string) (string, error) {
	cwd := resolveRetitleCWD(meta, currentChatPath)
	if cwd == "" {
		return "", fmt.Errorf("cwd is required to rename auto-generated chat path")
	}
	return buildUniqueChatPath(cwd, nextTitle)
}

func (s *Service) RetitleThread(
	ctx context.Context,
	query op.ThreadMetaQuery,
	title string,
) (*op.ThreadMeta, error) {
	nextTitle := strings.TrimSpace(title)
	if nextTitle == "" {
		return nil, fmt.Errorf("title is required")
	}

	meta, err := s.GetThreadMeta(ctx, query)
	if err != nil {
		return nil, err
	}

	currentTitle := strings.TrimSpace(meta.Title)
	currentChatPath := strings.TrimSpace(meta.Path)
	if currentChatPath == "" {
		currentChatPath = strings.TrimSpace(meta.ChatPath)
	}
	nextChatPath := currentChatPath
	if shouldMigrateRetitledChatPath(meta, currentChatPath, nextTitle) {
		nextChatPath, err = buildRetitledChatPath(meta, currentChatPath, nextTitle)
		if err != nil {
			return nil, err
		}
	}

	rollbackProjection, err := prepareProjectionRetitle(
		currentChatPath,
		nextChatPath,
		currentTitle,
		nextTitle,
		meta.ThreadID,
		meta.ParentThreadID,
	)
	if err != nil {
		return nil, err
	}
	rollbackIndex, err := applyRetitleIndexUpdate(meta, currentChatPath, nextChatPath, nextTitle)
	if err != nil {
		if rollbackProjection != nil {
			rollbackProjection()
		}
		return nil, err
	}

	updated, err := s.UpdateThreadMeta(ctx, op.ThreadMetaUpdateParams{
		ThreadID: meta.ThreadID,
		FileID:   meta.FileID,
		ChatPath: nextChatPath,
		Title:    nextTitle,
	})
	if err != nil {
		if rollbackIndex != nil {
			rollbackIndex()
		}
		if rollbackProjection != nil {
			rollbackProjection()
		}
		return nil, err
	}
	return updated, nil
}

func applyRetitleIndexUpdate(
	meta *op.ThreadMeta,
	currentChatPath string,
	nextChatPath string,
	nextTitle string,
) (func(), error) {
	currentChatPath = strings.TrimSpace(currentChatPath)
	nextChatPath = strings.TrimSpace(nextChatPath)
	nextTitle = strings.TrimSpace(nextTitle)
	if meta == nil || nextChatPath == "" || currentChatPath == nextChatPath {
		return nil, nil
	}

	var rollbacks []func()
	rollbackAll := func() {
		for i := len(rollbacks) - 1; i >= 0; i-- {
			rollbacks[i]()
		}
	}

	threadID := strings.TrimSpace(meta.ThreadID)
	fileID := strings.TrimSpace(meta.FileID)
	agentID := normalizeThreadAgentID(meta.AgentID)
	cwd := resolveRetitleCWD(meta, currentChatPath)
	if cwd != "" && fileID != "" && threadID != "" {
		var previous *chatindex.FileRecord
		if record, err := chatindex.ResolveFileRecord(cwd, fileID); err == nil && record != nil {
			copy := *record
			previous = &copy
		} else if err != nil && !os.IsNotExist(err) {
			return nil, err
		}
		if err := chatindex.UpsertFileRecord(cwd, chatindex.FileRecord{
			FileID:   fileID,
			AgentID:  agentID,
			ThreadID: threadID,
			CWD:      cwd,
			Path:     nextChatPath,
		}); err != nil {
			return nil, err
		}
		rollbacks = append(rollbacks, func() {
			if previous != nil {
				_ = chatindex.UpsertFileRecord(cwd, *previous)
				return
			}
			_ = chatindex.RemoveFileRecord(cwd, fileID)
		})
	}

	threadFilePath := strings.TrimSpace(meta.ThreadFilePath)
	if threadID != "" && threadFilePath != "" {
		var previous *chatindex.ThreadRecord
		if record, err := chatindex.FindThreadRecordByThreadIDAtRoot(filepath.Dir(threadFilePath), threadID); err == nil && record != nil {
			copy := *record
			previous = &copy
		} else if err != nil && !os.IsNotExist(err) {
			rollbackAll()
			return nil, err
		}

		nextRecord := chatindex.ThreadRecord{
			ThreadID: threadID,
			AgentID:  agentID,
			FileID:   fileID,
			CWD:      cwd,
			ChatPath: nextChatPath,
			Path:     threadFilePath,
			Title:    nextTitle,
		}
		if err := chatindex.UpsertThreadRecordForThreadFile(threadFilePath, nextRecord); err != nil {
			rollbackAll()
			return nil, err
		}
		rollbacks = append(rollbacks, func() {
			if previous != nil {
				_ = chatindex.UpsertThreadRecordForThreadFile(threadFilePath, *previous)
				return
			}
			if agentID != "" {
				_ = chatindex.RemoveThreadRecord(agentID, threadID)
			}
		})
	}

	return rollbackAll, nil
}

func prepareProjectionRetitle(
	currentPath string,
	nextPath string,
	currentTitle string,
	nextTitle string,
	threadID string,
	parentThreadID string,
) (func(), error) {
	currentPath = strings.TrimSpace(currentPath)
	nextPath = strings.TrimSpace(nextPath)
	currentTitle = strings.TrimSpace(currentTitle)
	nextTitle = strings.TrimSpace(nextTitle)
	threadID = strings.TrimSpace(threadID)
	parentThreadID = strings.TrimSpace(parentThreadID)

	if nextPath == "" {
		return nil, fmt.Errorf("chatPath is required")
	}

	if currentPath == nextPath {
		if err := rewriteProjectionChatTitle(nextPath, nextTitle, threadID, parentThreadID); err != nil {
			return nil, err
		}
		return func() {
			_ = rewriteProjectionChatTitle(nextPath, currentTitle, threadID, parentThreadID)
		}, nil
	}

	if err := os.MkdirAll(filepath.Dir(nextPath), 0o755); err != nil {
		return nil, err
	}

	renamed := false
	if currentPath != "" {
		if err := os.Rename(currentPath, nextPath); err == nil {
			renamed = true
		} else if !os.IsNotExist(err) {
			return nil, err
		}
	}
	if !renamed {
		if err := createProjectionFile(threadID, "", nextTitle, nextPath, parentThreadID); err != nil {
			return nil, err
		}
		return func() {
			_ = os.Remove(nextPath)
		}, nil
	}
	if err := rewriteProjectionChatTitle(nextPath, nextTitle, threadID, parentThreadID); err != nil {
		_ = os.Rename(nextPath, currentPath)
		_ = rewriteProjectionChatTitle(currentPath, currentTitle, threadID, parentThreadID)
		return nil, err
	}
	return func() {
		_ = os.Rename(nextPath, currentPath)
		_ = rewriteProjectionChatTitle(currentPath, currentTitle, threadID, parentThreadID)
	}, nil
}

func rewriteProjectionChatTitle(
	chatPath string,
	title string,
	threadID string,
	parentThreadID string,
) error {
	chatPath = strings.TrimSpace(chatPath)
	title = strings.TrimSpace(title)
	threadID = strings.TrimSpace(threadID)
	parentThreadID = strings.TrimSpace(parentThreadID)
	if chatPath == "" {
		return fmt.Errorf("chatPath is required")
	}

	content, err := os.ReadFile(chatPath)
	if err != nil {
		if os.IsNotExist(err) {
			return createProjectionFile(threadID, "", title, chatPath, parentThreadID)
		}
		return err
	}

	text := strings.ReplaceAll(string(content), "\r\n", "\n")
	if !strings.HasPrefix(text, "---\n") {
		return fmt.Errorf("chat markdown missing canonical frontmatter")
	}
	end := strings.Index(text[4:], "\n---\n")
	if end < 0 {
		return fmt.Errorf("chat markdown missing canonical frontmatter terminator")
	}
	end += 4
	frontmatterLines := strings.Split(text[4:end], "\n")
	nextLines := make([]string, 0, len(frontmatterLines)+1)
	replaced := false
	for _, line := range frontmatterLines {
		if strings.HasPrefix(strings.ToLower(strings.TrimSpace(line)), "title:") {
			nextLines = append(nextLines, "title: "+strconv.Quote(title))
			replaced = true
			continue
		}
		nextLines = append(nextLines, line)
	}
	if !replaced {
		nextLines = append(nextLines, "title: "+strconv.Quote(title))
	}
	nextContent := strings.Join([]string{
		"---",
		strings.Join(nextLines, "\n"),
		"---" + text[end+4:],
	}, "\n")
	return os.WriteFile(chatPath, []byte(nextContent), 0o644)
}
