import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const source = readFileSync(path.join(__dirname, 'chatService.ts'), 'utf8');

test('created chats open the backing conversation tab in the primary editor', () => {
  assert.match(source, /function ensureCreatedChatTab\(/);
  assert.doesNotMatch(source, /conversationFilePinned/);
  assert.match(source, /void ws\.openThreadTab\(chatPath, title, initialContent \|\| ''\);/);
  assert.doesNotMatch(source, /retargetActiveBlankTab\(chatPath, title, initialContent\)/);
  assert.doesNotMatch(source, /ws\.ensureThreadTab\(chatPath, title, initialContent/);
});

test('pending chat sends clear the submitted draft before create returns', () => {
  assert.doesNotMatch(source, /shouldDelayDraftClear/);
  const clearIndex = source.indexOf("chatState.setDraftForTarget(initialTarget, '');");
  const accessIndex = source.indexOf("chatAccessAllowed = await ensureChatAccessOrPrompt('chat');");
  const createIndex = source.indexOf('const created = await createChat(');

  assert.ok(clearIndex >= 0, 'submitted draft should be cleared');
  assert.ok(accessIndex >= 0, 'chat access preflight should exist');
  assert.ok(createIndex >= 0, 'chat create call should exist');
  assert.ok(clearIndex < accessIndex, 'draft should clear before async chat access preflight');
  assert.ok(clearIndex < createIndex, 'draft should clear before create returns');
  assert.match(source, /rollbackSubmittedRun\(runningTarget, chatPathToStream\);/);
});

test('submitted draft restore does not overwrite a new draft', () => {
  assert.match(
    source,
    /if \(latestState\.getDraftForTarget\(target\)\) \{\s*return;\s*\}/m,
  );
});

test('new chat runs prepare the live overlay before streaming', () => {
  const prepareCalls = source.match(/prepareLiveOverlayForNewRun\(chatPathToStream\)/g) || [];
  assert.equal(prepareCalls.length, 1);
  assert.match(source, /chatState\.prepareLiveOverlayForNewRun\(chatPathToStream\);\s*chatState\.setActivityExpanded\(chatPathToStream, true\);/);
  assert.match(source, /chatState\.prepareLiveOverlayForNewRun\(activityKey\);/);
  assert.doesNotMatch(source, /pushLiveUserInput/);
});

test('chat review refresh resolves the thread before listing reviews', () => {
  assert.match(source, /const threadMeta = chatState\.getThreadMeta\(normalized\)\s+\|\| await getRuntimeThreadMeta\(buildThreadLookupByPath\(normalized, workspaceTabId\), workspaceTabId\)\.catch\(\(\) => null\);/);
  assert.match(source, /const reviewThreadID = \(threadMeta\?\.threadID \|\| ''\)\.trim\(\);/);
  assert.match(source, /listThreadReviews\(reviewThreadID\)/);
  assert.doesNotMatch(source, /listThreadReviews\(normalized\)/);
});

test('auto-named chats retitle from existing title before new prompt text', () => {
  assert.match(source, /export function resolveAutoRetitleTitle\(/);
  assert.match(source, /isAutoGeneratedChatPath\(threadMeta\.chatPath \|\| threadMeta\.path\)/);
  assert.match(source, /if \(currentTitle && !isAutoGeneratedChatTitle\(currentTitle\)\) \{\s*return currentTitle;\s*\}/m);
  assert.match(source, /const autoRetitleTitle = resolveAutoRetitleTitle\(threadMeta, nextAutoTitle\);/);
  assert.match(source, /title: autoRetitleTitle,/);
  assert.doesNotMatch(source, /shouldAutoRetitleChat/);
});

test('chat submission sends modelKey without legacy model', () => {
  assert.match(source, /modelKey: effectiveModelKey/);
  assert.doesNotMatch(source, /resolveProviderFacingModelID/);
  assert.doesNotMatch(source, /requestModelID/);
  assert.doesNotMatch(source, /model:\s*requestModelID/);
});

test('chat submission does not resolve empty model selections through Auto or Default Chat fallback', () => {
  assert.doesNotMatch(source, /resolveAutoStrategyChat/);
  assert.doesNotMatch(source, /autoThinkingLevel/);
  assert.match(source, /No chat model is selected\. Open Models > Policies/);
});

test('chat submission sends per-model preference meta instead of global thinking state', () => {
  assert.match(source, /function resolveExecutionModelPreferenceMeta\(/);
  assert.match(source, /resolveChatModelPreference\(useModelsStore\.getState\(\)\.config, effectiveModel\)/);
  assert.match(source, /\.\.\.executionModelMeta/);
  assert.doesNotMatch(source, /useUiStore\.getState\(\)\.chatThinkingLevel/);
});

test('manual compact sends the active model preference meta', () => {
  assert.match(source, /export async function compactCurrentThread\(\)/);
  assert.match(source, /const selectedModelKey = chatState\.getSelectedModelKey\(\);/);
  assert.match(source, /const \{ effectiveModelKey, effectiveModel, errorMessage \} = resolveExecutionModelConfig\(/);
  assert.match(source, /const executionModelMeta = resolveExecutionModelPreferenceMeta\(effectiveModel\);/);
  assert.match(source, /opcode: 'thread\/compact'[\s\S]*modelKey: effectiveModelKey,[\s\S]*\.\.\.executionModelMeta,/m);
});

test('thread snapshot window loading merges bounded windows and resets stale revisions', () => {
  assert.match(source, /export async function loadThreadSnapshotWindow\(/);
  assert.match(source, /assertWindowedThreadSnapshot\(snapshot\);/);
  assert.match(source, /options\.mode !== 'tail'[\s\S]*current\.revision[\s\S]*snapshot\.revision[\s\S]*refreshThreadStateByThreadID/m);
  assert.match(source, /snapshotDirectionForEntryWindow\(snapshot\.entryWindow\?\.mode \|\| options\.mode\)/);
  assert.match(source, /syncThreadSnapshotState\(workspaceTabId, snapshot, \{ direction \}\)/);
  assert.match(source, /entryWindow: ThreadSnapshotEntryWindowQuery = \{/);
});
