/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/renderer/**/*.{js,ts,jsx,tsx}",
    "./src/renderer/styles/**/*.css",
  ],
  theme: {
    extend: {
      colors: {
        'editor-bg': 'var(--color-editor-bg)',
        'editor-fg': 'var(--color-editor-fg)',
        'sidebar-bg': 'var(--color-sidebar-bg)',
        'sidebar-fg': 'var(--color-sidebar-fg)',
        'titlebar-bg': 'var(--color-titlebar-bg)',
        'border': 'var(--color-border)',
        'active-border': 'var(--color-active-border)',
        'accent': 'var(--color-accent)',
        'accent-hover': 'var(--color-accent-hover)',
        'hover-bg': 'var(--color-hover-bg)',
        'secondary-hover-bg': 'var(--color-secondary-hover-bg)',
        'selection': 'var(--color-selection)',
        'search-match-bg': 'var(--color-search-match-bg)',
        'search-match-text': 'var(--color-search-match-text)',
        'highlight': 'var(--color-highlight)',
        'button-bg': 'var(--color-button-bg)',
        'button-bg-hover': 'var(--color-button-bg-hover)',
        'button-text': 'var(--color-button-text)',
        'link-text': 'var(--color-link-text)',
        'link-text-hover': 'var(--color-link-text-hover)',
        'prime-text': 'var(--color-prime-text)',
        'secondary-text': 'var(--color-secondary-text)',
        'tertiary-text': 'var(--color-tertiary-text)',
        'logo-light': 'var(--color-logo-light)',
        'logo-dark': 'var(--color-logo-dark)',
        'trigram-yao': 'var(--color-trigram-yao)',
        'health-text': 'var(--color-health-text)',
        'background': 'var(--color-background)',
        'secondary-bg': 'var(--color-secondary-bg)',
        'overlay-bg': 'var(--color-overlay-bg)',
      },
    },
  },
  plugins: [],
};
